- name: Create Dockerfile for a basic html/css web application
  hosts: localhost
  tasks:
    - name: Create Dockerfile
      ansible.builtin.copy:
        dest: ./Dockerfile
        content: |
          # Use an official Nginx image as the base image
          FROM nginx:alpine

          # Copy the HTML and CSS files to the Nginx web root directory
          COPY app/index.html /usr/share/nginx/html/index.html
          COPY app/styles.css /usr/share/nginx/html/styles.css

          # Expose port 80 for the web server
          EXPOSE 80

          # Start Nginx when the container starts
          CMD ["nginx", "-g", "daemon off;"]
