name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: eu-west-1
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  terraform:
    name: "1 — Terraform Apply"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

      - name: Save EC2 IP
        run: |
          IP=$(terraform output -raw public_ip)
          echo "EC2_IP=$IP" >> $GITHUB_ENV
        working-directory: ./terraform

  #  build:
  #    name: "2 — Build & Push Docker Image"
  #    needs: terraform
  #    runs-on: ubuntu-latest
  #    permissions:
  #      contents: read
  #      packages: write
  #    steps:
  #      - uses: actions/checkout@v4
  #
  #      - name: Log in to GHCR
  #        uses: docker/login-action@v3
  #        with:
  #          registry: ghcr.io
  #          username: ${{ github.actor }}
  #          password: ${{ secrets.GITHUB_TOKEN }}
  #
  #      - name: Build and Push
  #        uses: docker/build-push-action@v6
  #        with:
  #          context: .
  #          push: true
  #          tags: ${{ env.DOCKER_IMAGE }}:latest

  deploy:
    name: "3 — Ansible Deploy"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible & Collections
        run: |
          pip install ansible
          ansible-galaxy collection install amazon.aws community.docker

      - name: Write SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ansible-user
          chmod 600 ~/.ssh/ansible-user

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory/aws_ec2.yml ansible/playbook_web_server.yml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ANSIBLE_HOST_KEY_CHECKING: "false"
